/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package interfaz;

/**
 *
 * @author Liz
 */
public class VentanaPedido extends javax.swing.JFrame {

    /** Creates new form VentanaPedido */
    public VentanaPedido() {
        initComponents();   
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ff = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        dcfghjui = new javax.swing.JTextField();
        dfghjkio = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        popp = new javax.swing.JButton();
        p99kijuhyt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(26, 32, 58));
        jPanel1.setPreferredSize(new java.awt.Dimension(710, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Agency FB", 0, 48)); // NOI18N
        jLabel1.setText("Pedidos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jLabel2.setText("Cantidad:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        ff.setBackground(new java.awt.Color(204, 204, 204));
        ff.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        ff.setForeground(new java.awt.Color(0, 0, 0));
        ff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ffActionPerformed(evt);
            }
        });
        jPanel1.add(ff, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 30, -1));

        jLabel3.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jLabel3.setText("Seleccione almacén:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        dcfghjui.setBackground(new java.awt.Color(204, 204, 204));
        dcfghjui.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        dcfghjui.setForeground(new java.awt.Color(0, 0, 0));
        dcfghjui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dcfghjuiActionPerformed(evt);
            }
        });
        jPanel1.add(dcfghjui, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 100, -1));
        jPanel1.add(dfghjkio, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jLabel4.setText("Indique producto:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        popp.setText("Hacer pedido");
        popp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poppActionPerformed(evt);
            }
        });
        jPanel1.add(popp, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 120, -1));

        p99kijuhyt.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        p99kijuhyt.setText("Regresar al menú");
        jPanel1.add(p99kijuhyt, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, 150, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void ffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ffActionPerformed

    private void dcfghjuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dcfghjuiActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_dcfghjuiActionPerformed

    private void poppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poppActionPerformed
        // TODO add your handling code here:        
    }//GEN-LAST:event_poppActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dcfghjui;
    private javax.swing.JSpinner dfghjkio;
    private javax.swing.JTextField ff;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton p99kijuhyt;
    private javax.swing.JButton popp;
    // End of variables declaration//GEN-END:variables
}
}
